AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/EndOfLine:
  Enabled: False

Metrics/BlockLength:
  Exclude:
    - 'lab1/spec/**/*_spec.rb'
    - 'lab2/spec/**/*_spec.rb'
    - 'lab3/spec/**/*_spec.rb'
